### ISSUE TITLE
Deselecting all panel labels throws exception

### ISSUE THREAD

**Issue by lhsego** [tesseradata/trelliscope#107]
If **all** the Panel Labels are deselected, an error is thrown.   It does recover is at least one label is selected. Would be good to protect user against this by not letting them deselect all labels.

**Comment by hafen** [comment]
I can't replicate this using the latest.  Do you have an example?  No labels should be a valid option.

**Comment by lhsego** [comment]
Hmmm..I can't replicate it either!  I was using the latest version.  All I can think is that I might have done a series of actions that led to the error--but what those trigger actions might be, I have no idea.  So guess we should just close this for now.

**Comment by hafen** [comment]
Strange.  If you track it down again, if you are are running it locally, can you paste the output from your R console that is printed after calling `view()`.  Also, if you [open up the javascript console](http://webmasters.stackexchange.com/questions/8525/how-to-open-the-javascript-console-in-different-browsers) in your web browser, if you can paste any output there that would be helpful.
