### ISSUE TITLE
makeDisplay panelFn check ignores params argument.

### ISSUE THREAD

**Issue by jrounds** [tesseradata/trelliscope#119]
Hi,

I am a building a package to do protein displays using trelliscope.  I don't want to use the global scope much.

This issue is about the interaction of "panelFn" and "params" argument of makeDisplay.

At the start of a makeDisplay, Trelliscope trys a test panelFn, but if you have a panelFn that depends on a param in params it won't be found in scope unless that param is also in the global scope when makeDisplay runs.  It seems to me the test of panelFn should be in an environment that contains params when it is utilized.  That both alleviates the need to put objects in the calling environment for makeDisplay and actually does a slightly more relevant test to distributed computing.

I think this could be done simply by changing the environment of panelFn in a copy of the panelFn argument to be as.environment(params).  For example at line 128 here:
https://github.com/tesseradata/trelliscope/blob/master/R/makeDisplay.R

Change it to:
if(!is.null(params)){
  panelFn2 = panelFn
  environment(panelFn2) = as.environment(params)
  panelEx <- kvApply(kvExample(data), panelFn2)$value
} else {
  panelEx <- kvApply(kvExample(data), panelFn)$value
}
It basically says if you give params it should be everything you need to run panels.

Note: this code change has never been tested in R.  I just wrote it here, it may not even work right =)

**Comment by jrounds** [comment]
Closing because on the way home I was thinking... a simple "with(params, makeDisplay(...))" might be sufficient at the user level.

**Comment by hafen** [comment]
Sorry I'm late on this.  It would indeed be good and the right thing to do to include params in the test instead of leaving it up to the user.  I hadn't thought of that as a potential issue (naively supposed anything specified in `params` would be on the search path).  I'm going to reopen this.

I think really all that would be needed would be to change 

```
panelEx <- kvApply(kvExample(data), panelFn2)$value
```

to 

```
panelEx <- with(params, kvApply(kvExample(data), panelFn2)$value)
```

It's so easy, you can make the change and test on your example and submit a pull request! :)

**Comment by jrounds** [comment]
Because this issue is masking my ability to figure something else out,
I spent an hour trying this (and variants) 
```
panelEx <- with(params, kvApply(kvExample(data), panelFn2)$value)
```

That is one way that does not work =)

```
panelFn = function(v) {
		title.local = title0
		plot(1:10, main=title.local)
		return(NULL)
}
rm(title0) #just in case

data(iris)
ddo0 = divide(iris, by="Species")
tmp = tempfile()
vdb = vdbConn(tmp, "temp",autoYes=TRUE)
makeDisplay(ddo0, panelFn=panelFn, cogFn = function(v) list(cog=1), name="tmp", conn=vdb, 
	params=list(title0="respect_my_authority"))
```

```
* Validating 'panelFn'...
Error in fn(kvPair[[2]]) : object 'title0' not found
```

**Comment by jrounds** [comment]
Side issue: changing that line is not sufficient because of thumbnail.

Bigger issue:

I sort of made progress by just changing the environment of the panelFn (here https://github.com/jrounds/trelliscope/blob/check_panelFn_with_params/R/makeDisplay.R#L128); however, that bit on panelFn that call other panelFn that assume they will see a parameter in the global environment.

e.g.
foo = function(v) goo(v)

since foo got changed goo (in a package) did not necessarily get changed and goo might have thought there was going to be a global.

**Comment by jrounds** [comment]
I decided the obvious work around was to only let the outer function assume global environment variables and force the inner function to use arguments.

e.g. (not runnable)
```

panelHeatmap.DDOPepByPro = function(v,  heat_color_var = c("mean", "fold_change"), title,
	omicsTrelliscopeMeta){
	meta = omicsTrelliscopeMeta
	#names(meta)
		#meta = get("omicsTrelliscopeMeta") #just to be clear
	#	x = meltPeptideMatrix(v$peptide.data, meta$group.data)
	#	x = as.data.table(x)
	#	res = x[,  peptideStatisticsMelted(.SD, meta$format), by="Peptide"]
	n = rownames(v$abundance)
	res = copy(meta$peptide_statistics_long[n])
	data = res
	labels = levels(data$Group)
	#data = subset(res, !is.na(mean) & !is.na(fold_change))
	data = as.data.table(data)
	format = as.data.table(meta$format)
	setkeyv(data, "Group")
	setkeyv(format, "Group")
	data = format[data]
	data = as.data.frame(data)

	data$peptide_display_name = meta$peptide_display_name[data$Peptide]
	#data ops based on color var
	switch(heat_color_var, 
		mean = {
			data$quantile_of_control = round( meta$control_mean_ecdf(data$mean),3)
		},
		fold_change = {
			data = subset(data, !Control) 
		}
	)
		
		
	DO_PLOT = sum(!is.na(data[[heat_color_var]])) > 1 
	#ytext = NULL
	#if(length(unique(data$Peptide)) > 40)
	#			ytext= theme(axis.text.y = element_blank())
#	data = subset(data, !is.na(data[[heat_color_var]]))
	hover_data = rbokehHoverData(data,colnames(meta$peptide_statistics_long))
	
	
	#p = figure(title="Mean",height=800,width=800,xgrid = FALSE, ygrid = FALSE, xlab = "Group", ylab = "Peptide", xlim=levels(meta$format$Group))
	p = figure(title=title,tools="hover",height=800,width=800,xgrid = FALSE, ygrid = FALSE, xlab = "Group", ylab = "Peptide", xlim=levels(meta$format$Group))
	if(DO_PLOT){
		switch( heat_color_var,
			mean = {
			p  = p %>% ly_heatmap(x=Group, y=peptide_display_name, value=mean, data=data, 
				colorQuantileFn=meta$control_mean_ecdf, 	hover=hover_data) 
			},
			fold_change = {
			p = p %>% ly_heatmap(x=Group, y=peptide_display_name, value=fold_change,
				data=data,  	hover=hover_data)
			},
			default = {stop("Add plotting code for type " , p)} 
		)
		
		p = p %>%	x_axis(major_label_orientation = 90)	
	}
	#})
	p
	
}

panelHeatmapFoldChange.DDOPepByPro = function(v)
			panelHeatmap.DDOPepByPro(v, "fold_change", "Fold Change", omicsTrelliscopeMeta)

panelHeatmapMean.DDOPepByPro = function(v) 
	panelHeatmap.DDOPepByPro(v, "mean", "Mean", omicsTrelliscopeMeta)
```

Initiating pull request.

**Comment by jrounds** [comment]
Fixed
