### ISSUE TITLE
What do you think I need to install?

### ISSUE THREAD

**Issue by jrounds** [tesseradata/trelliscope#125]
This view result is on a centosOS 6.5 set up in a cloud tenant.  The person that set it up tested trelliscope in rstudio, but I want to be able to run trelliscope from an ssh/terminal.   I have sudo.  What do you think I should install to get past this?
```
> view(conn=conn)
attempting to launch shiny vdb viewer...
press Ctrl+C or Esc to stop viewer

Listening on http://127.0.0.1:8100
/usr/bin/xdg-open: line 402: htmlview: command not found
/usr/bin/xdg-open: line 402: firefox: command not found
/usr/bin/xdg-open: line 402: mozilla: command not found
/usr/bin/xdg-open: line 402: netscape: command not found
/usr/bin/xdg-open: line 402: links: command not found
/usr/bin/xdg-open: line 402: lynx: command not found
xdg-open: no method available for opening 'http://127.0.0.1:8100'
```

**Comment by jrounds** [comment]
The person that set up the Rstudio server said I would probably need to install X11 port forwarding

**Comment by hafen** [comment]
Don't do x11 - that is painfully slow.  Try ssh like this:

```
ssh \
  -L 8101:127.0.0.1:8101 \
  user@ip
```

Also you can check out this package for letting you see your plots, etc. over a remote session without x11 as well: https://github.com/hafen/rmote

**Comment by hafen** [comment]
Oops I meant 8100:127.0.0.1:8100

**Comment by jrounds** [comment]
Thanks for the suggestions!
