### ISSUE TITLE
Putting common globals on a diet (pull request)

### ISSUE THREAD

**Issue by jrounds** [tesseradata/trelliscope#130]
Hi,

The current global detection scheme of trelliscope places into each display the detected global variables.  If each display works off a common set of global variables this is incredibly wasteful.  For example,  a 70mb global data set takes 20 seconds to read/write on my computer.  If each display copies it that is 70mb and 20 seconds per a display.    It is wasteful when the panels load via view (since each is loading their own copy of globals) and it is wasteful in disk-space.

There was a simple fix and that was to include the idea of "by-hand" globals that are truly global for the connection object (I had imagined group-globals, but alas that isn't in the cards.) This touches other aspects or usages of trelliscope minimally: if you don't use it you don't notice it.

I am initiating a pull request with these changes:

1) new function saveGlobals(..., conn)  writes data to globals.Rdata in the vdbconn.

2) aded global.R file for shiny that loads globals.Rdata if exists.

3) detect.globals is now an argument in makeDisplay().  If FALSE it disables the detection of globals by trelliscope (this is because I have found it to be unreliable in some use-cases and over-enthusiastic in other cases and also it makes panelFn harder to debug (because if there is accidently a global in a panelFn that you didn't want to be global trelliscope will "fix-it-up" when you really wanted to know about it).

4) I added a test_that file (but I don't know much about test_that)

5) added code to the copy trelliscopeViewer function to copy new global.R file.

TODO:
Not sure how this would play out with some of Trelliscopes less used features

What does it look like in code:
```
conn = vdbconnvs = vdbConn(file.path(wdisplay,"vdb_vs"), name = "jr_omicscope_demo", autoYes=TRUE)
system.time({trelliscope:::saveGlobals(omicsTrelliscopeMeta, conn=conn)})
makeDisplay.DDOPepByPro(pbp_vs, "survival", conn=vdbconnvs)
makeDisplay.DDOPepByPro(pbp_vs, "boxplot", conn=vdbconnvs)
makeDisplay.DDOPepByPro(pbp_vs, "mean_heatmap", conn=vdbconnvs)
makeDisplay.DDOPepByPro(pbp_vs, "foldchange_heatmap", conn=vdbconnvs)
rm(omicsTrelliscopeMeta)
view(conn=vdbconnvs)
```

Where the system.time is at 20 seconds and that used to be 20 seconds in each of the makeDisplay calls (which was repeated when the displays were loaded).

**Comment by hafen** [comment]
Thanks for all these fixes!  Sorry I've been unresponsive - I've been out of the country for the last few weeks.  I'll take a look at these early next week and merge them in.

**Comment by jrounds** [comment]
There is really four things muddled in there now
1) fix for params argument not being used in panelFn check (opinion: works)
2) flag to turn off adding global params in makeDisplay (useful for debugging scenarios) (opinion:works)
3) saveGlobal functions and supporting code to load globals when trelliscope viewer starts (opinion: works* see comment).
4) copyView (opinion: doesn't work. see comment)


About (3), saveGlobals.  I actually do need this for a largish data set where I want to keep data out of the panels, but I learned enough about trelliscope internals now that I could easily hack this in around trelliscope code, so no need to add it.  For example, just dropping global.R will force shiny to load globals.Rdata and trelliscope server.R won't even get involved, so there is no particular need to add it.

About (4), copyView wasn't supposed to be in this branch.  I am starting to think a "copy-mutate" work flow for views would make trelliscope work kindly on Hadoop systems.  Meaning, you make a makeDisplay and then you mutateDisplay() and change aspects of it hopefully without starting a MapReduce.  copyDisplay was a precursor idea, where you would copy a display and then mutate it and then copy it back.  Not really necessary but useful.  Doesn't work yet.  Some reason the display doesn't show up reliably.  Cut out the .R file.

**Comment by jrounds** [comment]
I had to re-organize this a little bit while using it.
Two things crossed my desk this morning (from a stack of post-it notes). 
1) Sharing my vdb with a collaborator on an environment where my R package was not yet deployed.
2) Sharing my vdb on shiny apps.

(2) made me realize I had picked the wrong spot for globals.Rdata.  The "shiny-way" has it in data/globals.Rdata.  I made that adjustment.

(1) was a little weird and interacted with (2).  I had been writing all my trelliscope material in an R package, but doing that and using shinyapps forces you to deploy and install the R package from github.  Also my collaborator couldn't get the R package on the development environment because it had not be hooked into a continuous ingestion system.

So what I did was re-wrote the new global.R in Trelliscope to source R code in data/R of the vdb, and then I wrote a function to copy R files to that directory from a source directory.

The result is then when you do something simple like
```
> library(trelliscope)
Loading required package: datadr
Loading required package: lattice
Loading required package: ggplot2
> conn = vdbConn(".")
*** Copying latest viewer to vdb directory...
> view(conn)
> view(conn=conn)
attempting to launch shiny vdb viewer...
press Ctrl+C or Esc to stop viewer
Loading required package: shiny
Loading data/globals.Rdata
Sourcing data/R
data/R/biomaRtOps.R
data/R/cognostics.R
data/R/DDOAbundance.R
data/R/DDOPepByPro_Panels.R
data/R/DDOPepByPro.R
data/R/DDOPeptide.R
data/R/DDOProtein.R
data/R/EnsemblGTFOps.R
data/R/getPeptideDisplayNames.R
data/R/KVMeta.R
data/R/ly_heatmap.R
data/R/ly_kaplanMeier.R
data/R/makeDisplay.R
data/R/melt.R
data/R/omicsRExtensions.R
data/R/panelBoxplot.R
data/R/panelHeatmap.R
data/R/panelSurvival.R
data/R/panelVolcano.R
data/R/PeptideData.R
data/R/peptideStatistics.R
data/R/proteoformViz.R
data/R/StandardPreprocessing.R
data/R/tryPanel.R

```

Code to set that up looks like
```
conn = vdbconnvs = vdbConn(file.path(wdisplay,"vdb", "protein_vs"), name = "jr_omicscope_demo", autoYes=TRUE)
saveGlobals(omicsTrelliscopeMeta, conn=conn)  #HERE IS GLOBAL CODE
copyRSource("../R", conn=conn)  #HERE IS GLOBAL CODE
mode="make"
makeDisplay.DDOAbundance(protein_vs, "survival", conn=vdbconnvs,mode=mode)
makeDisplay.DDOAbundance(protein_vs, "boxplot", conn=vdbconnvs, mode=mode)
rm(omicsTrelliscopeMeta)
view(conn=vdbconnvs)
```
In this way I handled the problem of not having to tell people about extra R functions, but they should also go with shiny deployments.

At the moment I am testing whether or not this deploys to shinyApps easily but it is all in 
https://github.com/tesseradata/trelliscope/compare/master...jrounds:develop

**Comment by hafen** [comment]
This is merged.
