### ISSUE TITLE
Small bug fix: copyViewerFiles had inconsistent overwrite defaults.

### ISSUE THREAD

**Issue by jrounds** [tesseradata/trelliscope#133]
I have merged up everything into a personal develop branch on a fork rather than trying to keep every small bug fix in a separate branch (sorry that keeps me from dog-fooding and at the moment I am dog fooding these changes in two large projects that are very different and that is nice)

I noticed copyViewerFiles relied on defaults from copy.file for the over-write option, and the default is different for recursive or not recursive: result server.R never got copied into a pre-existing vdb directory.

The effected lines are here:
https://github.com/jrounds/trelliscope/blob/40a3e98953e9c1fcc492819b323a8ee3c981988d/R/view.R#L85

When recursive is true it was over-writing, but when recursive was default it was not.

**Comment by hafen** [comment]
I think this is fixed now?  Can you check and close, @jrounds?

**Comment by jrounds** [comment]
yeah I fixed that while I was touching that code so that it would always
overwrite.

**Comment by hafen** [comment]
Thanks.
