### ISSUE TITLE
Trelliscope on ports other than 8100

### ISSUE THREAD

**Issue by clintidau** [tesseradata/trelliscope#139]
We are attempting to use Tessera on a multi-user server with RStudio-Server. After the first user launches Trelliscope, every other user fails with this message:

>Listening on http://127.0.0.1:8100
>Error in startServer(host, port, handlerManager$createHttpuvApp()) : 
>  Failed to create server

Is it possible to make Trelliscope retry on port 8101, 8102 etc if port 8100 is already in use?

**Comment by hafen** [comment]
Thanks - that's a good suggestion.  I just committed an update that modifies the way ports are handled to more reflect how shiny handles it.  If a port is not specified, it will first look for an R global option "trelliscopePort".  If that is not specified, it will look for a system environment variable "TRELLISCOPE_PORT".  If that is not specified, it will let shiny assign a random port between 3000 and 8000.  With this, there is still a small chance of port collisions (I think - although maybe shiny checks for this).  If you want to be very sure that there are not collisions, you could have a different TRELLISCOPE_PORT environment variable set for each user.  Hope this addresses your issue.

**Comment by clintidau** [comment]
This works, thanks!
