### ISSUE TITLE
Trelliscope viewing requires write permission

### ISSUE THREAD

**Issue by jrounds** [tesseradata/trelliscope#147]
Hi,

Line https://github.com/hafen/trelliscope/blob/master/inst/trelliscopeViewer/server.R#L22

Executes:
https://github.com/tesseradata/trelliscope/blob/master/R/conn_vdb.R#L74

This essentially means that one cannot just view a trelliscope app without having write permission on that file.  Seems unnecessary in a  multi-user environment.  One idea is to put a try around the save's and warn rather than error if write permission is not available or have a "loading a deployed app" boolean.  

Want a pull request?

**Comment by hafen** [comment]
This is a good idea and would be an easy thing to do.  However, I believe there will be problems beyond this if there is not write access in the Trelliscope app directory.  For example, when rendering htmlwidgets in iframes, the individual html pages must be written to the app directory (I could get around this by storing the intermediate file in an everyone-writable temp directory and then reading and sending base64 encoded html to the iframe src, but I think that would be one more thing to slow things slow down).

Perhaps you can help me think of a case where it would not be possible for the user to have write access:

- If one is running a trelliscope app on their own machine, they should not have a problem with file permissions.
- If one is deploying to shiny server, that app will be run by the same user (shiny or whoever the user is set up for) regardless of who is logging on to view the app, so as part of the deployment process the app's permissions should be set to the user under which the app will be run.

**Comment by jrounds** [comment]
I think I just need to use a linux group for your second bullet point.  I didn't think about managing it from the linux side.  I will close now that the work around is clearer.

So the scenario that bigdatann is under is the shiny user needs to be the user running the app (implying the shiny user needs write permission), but I need to be the user making and writing to the app, and it seemed bad to give everyone write permission.

I was thinking I don't want to chown to give the shiny user the directory where I want to deploy too, but I am sure I could assign the directory to the group that shiny user is assigned to and give the group write permission without giving everyone write permission.
