### ISSUE TITLE
fix examples in cogScagnostics

### ISSUE THREAD

**Issue by jangorecki** [tesseradata/trelliscope#149]
There is an attempt to load `scagnostics` namespace in examples [cogScagnostics.Rd#L21](https://github.com/tesseradata/trelliscope/blob/master/man/cogScagnostics.Rd#L21), code below is the results from examples.
As `scagnostics` is suggested dependency, it should not be required to run examples according to [R-exts](https://cran.r-project.org/doc/manuals/R-exts.html#Suggested-packages). This can be conditionally escaped with `requireNamespace`.
It is possible there are other cases of that issue in other examples, this one was to first that fails.

```
* checking examples ... ERROR
Running examples in ‘trelliscope-Ex.R’ failed
The error most likely occurred in:

> base::assign(".ptime", proc.time(), pos = "CheckExEnv")
> ### Name: cogScagnostics
> ### Title: Compute Scagnostics
> ### Aliases: cogScagnostics
> 
> ### ** Examples
> 
> cogScagnostics(iris$Sepal.Length, iris$Sepal.Width)
Error: Package 'scagnostics' is needed for this function to work. Please install it.
Execution halted
```

**Comment by hafen** [comment]
Thanks for catching that!  I'll fix it.
