### ISSUE TITLE
cogDisplayHref displayGroup parameter is not optional

### ISSUE THREAD

**Issue by amwhite** [tesseradata/trelliscope#73]
In the cogDisplayHref function, the parameter displayGroup has a default value of NULL, but that leads to URLs that are invalid. The displayGroup parameter must be specified to get a valid URL. Recommend changing the default value to "common" instead, as this is the default group used by makeDisplay.

**Comment by hafen** [comment]
Good idea.  Thanks.  I think the plan there was to infer group by looking things up in the vdb with the supplied name.  But since these are specified beforehand, we can't do that.  "common" is a good default.
