### ISSUE TITLE
Visual Univariate Filter:  Barplots of Categorical Variables Not Resolving

### ISSUE THREAD

**Issue by lhsego** [tesseradata/trelliscope#75]
For example, look at this screen plot from the Housing example:

![screen shot 2015-01-29 at 10 52 22 pm](https://cloud.githubusercontent.com/assets/5566573/5972144/a8aebc2c-a809-11e4-8a42-43020e229580.png)

**Comment by hafen** [comment]
As we discussed offline, I'm disabling categorical variables in visual univariate filter view for now and will revisit when I have more bandwidth.
