### ISSUE TITLE
Code checking for version numbering

### ISSUE THREAD

**Issue by lhsego** [tesseradata/trelliscope#76]
Is there an easy way we can automatically check the following conditions:

- The version number is the same in NEWS.md, DESCRIPTION, and R/trelliscope-package.R
- The date is the same in DESCRIPTION and R/trelliscope-package.R

I was looking around at travis ci stuff, but it wasn't clear to me how that might work, since we'd be checking the code itself--not the execution of it.

**Comment by hafen** [comment]
I'm sure you could add in some bash commands to do this.  Feel free to experiment, but I would put it extremely low on the priority list.  Given the small number of contributors, it's easy enough to say to be careful checking versions when making commits.  Probably better to focus on more pressing issues.
