### ISSUE TITLE
trelliscope does not save all objects needed in vdb to view later

### ISSUE THREAD

**Issue by amwhite** [tesseradata/trelliscope#85]
This is a bug that has was introduced February 3. The code from the commit Jan 29 works as intended. 

Here's the problem: in the current version of trelliscope, if I create a vdb and in the process define a few functions and/or tertiary pieces of data needed for the plots. Trelliscope display works fine when calling view() in the same session. However, when I clear all variables and reconnect to the vdb and view it, errors are thrown because trelliscope appears to be looking for some function and/or variable I defined that is no longer in the R workspace.

Here's some example code to test, note my comments in the code about which display to look at for the error:

\# Load necessary libraries
library(datadr)
library(trelliscope)
library(housingData)

\# Remove any left-over objects in the Global environment
rm(list = ls())

\# Divide records by county and state
byCounty <- divide(housing, 
   by = c("county", "state"), update = TRUE)

\# byCounty is a Divided Data Frame one of the primary data types in datadr
class(byCounty)

\# Calculate linear model for each data division to see the trend in prices

\# Create a function to calculate a linear model and extract the slope parameter
lmCoef <- function(x) {
   data.frame(getSplitVars(x), slope=coef(lm(medListPriceSqft ~ time, data = x))[2])
}

\# Add the function transform to the DDF
byCountySlope <- addTransform(byCounty, lmCoef)

\# Recombine the slope data into a single data.frame
countySlopes <- recombine(byCountySlope, combRbind)

\#### Joining multiple data sets based on keys

\# Divide geoCounty on county and state just like we did with the housing data
geo <- divide(geoCounty, by = c("county", "state"))

\# Get some wikipedia data on counties and divide by county/state
wikiByCounty <- divide(wikiCounty, by = c("county", "state"))

\# Join divided housing, geo and wiki data together
\# This forms a Distributed Data Object (DDO)
joinedData <- drJoin(housing = byCounty, slope=byCountySlope, geo = geo, wiki=wikiByCounty)

\# Filter dataset to remove divisions without housing sales data
joinedData <- drFilter(joinedData, function(x) {
   !is.null(x$housing)
})

\#### Trelliscope: an interactive divide and recombine visualization tool

\# Define a visualization database directory where the plots and metadata
\# will be saved
vdbConn("vdb_housing", autoYes=TRUE)

\# Define a plot function
timePanel <- function(x) {
   xyplot(medListPriceSqft + medSoldPriceSqft ~ time,
      data = x$housing, auto.key = TRUE, ylab = "Price / Sq. Ft.")
}

\# Define a cognostics function: this is used to define information and 
\# statistics that will be available in the Trelliscope UI for sorting and 
\# filtering and also to display/link useful meta information.
priceCog <- function(a) { 
   x <- a$housing
   st <- getSplitVar(a, "state")
   ct <- getSplitVar(a, "county")
   zillowString <- paste(ct, st)
   zillowString <- gsub(" ", "-", zillowString)
   list(
      fips = cog(x$fips[1], desc = "fips code"),
      region = cog(state.region[state.abb == ifelse(st == "DC", "MD", st)]),
      division = cog(state.division[state.abb == ifelse(st == "DC", "MD", st)]),
      slope = cog(a$slope$slope, desc = "list price slope"),
      meanList = cogMean(x$medListPriceSqft),
      meanSold = cogMean(x$medSoldPriceSqft),
      listRange = cogRange(x$medListPriceSqft),
      soldRange = cogRange(x$medSoldPriceSqft),
      nObs = cog(length(which(!is.na(x$medListPriceSqft))), 
         desc = "number of non-NA list prices"),
      lat = cog(a$geo$lat, desc = "county latitude"),
      lon = cog(a$geo$lon, desc = "county longitude"),
      pop2013 = cog(log10(a$wiki$pop2013), desc = "log base 10 population in 2013"),
      wikiHref = cogHref(a$wiki$href, "wiki link"),
      zillowHref = cogHref(sprintf("http://www.zillow.com/homes/%s_rb/", zillowString), "zillow link")
   )
}

\# Create the display: this creates and saves display files and information in
\# the vdb directory defined above
makeDisplay(joinedData,
   name = "list_sold_vs_time_datadr_tut",
   desc = "List and sold price over time",
   panelFn = timePanel, 
   cogFn = priceCog,
   width = 400, height = 400,
   lims = list(x = "same"))

\# A second Trelliscope display based on maps

\# Filter out keys where either slope or geo data is missing
geoSlopeData <- drFilter(joinedData, function(x) {
   !is.null(x$slope) && !is.null(x$geo)
})

\# Combine slope and geo for each remaining division into a data.frame
\# (this eliminates the housing and wiki data)
geoSlopeData <- addTransform(geoSlopeData, function(x) {
   data.frame(x$slope, x$geo)
})

\# Create a dataset of county slope and geo data divided by state
slopesByState <- divide(geoSlopeData, by="state", update=TRUE)

\# Calculate slope percentiles for coloring the graphs
slopeQuantiles <- drQuantile(slopesByState, "slope")
slopePercentiles <- approx(slopeQuantiles$fval, slopeQuantiles$q, seq(0,1,by=0.01))$y

library(maps)

\# Match region definition from maps library to our state/county pairs
matchMapRegionToCounty <- function(mapRegionNames, countyNames) {
   ind <- match(mapRegionNames, countyNames)
   ind.na <- which(is.na(ind))

   for (i in ind.na) {
      ind[i] <- match(strsplit(mapRegionNames[i], ":")[[1]][1], countyNames)
   }
   ind
}

\# Create a state map of each county colored by price change
stateMapPanelFn <- function(x) {
   map.data <- map("county", x$rMapState[1], fill=TRUE, plot=FALSE)

   ind <- matchMapRegionToCounty(map.data$names, paste(x$rMapState, x$rMapCounty, sep=","))
   plot.colors <- rep("grey", times=length(map.data$names))
   plot.colors <- level.colors(x$slope,
      slopePercentiles, rainbow(n=100, start=0, end=2/6))[ind]
   plot.colors[is.na(plot.colors)] <- "grey"

   map(map.data, fill=TRUE, col=plot.colors)
   mtext(toupper(x$rMapState[1]))
   return(NULL)
}

\# Cognostics function that includes slope statistics, lat and lon ranges
\# and a link to the corresponding county plots for the selected state
mapCog <- function(x) {
   st <- getSplitVar(x, "state")
   
   trellState <- list(
      sort = list(county = "asc"),
      filter = list(
         state = list(select = st)
      ),
      layout = list(nrow = 2, ncol = 3),
      labels = c("county", "state")
   )
   validateState(trellState)
   
   list(
      countyPlots=cogDisplayHref("list_sold_vs_time_datadr_tut", 
         displayGroup="common", state=trellState, 
         label=paste("View county prices for", st), defLabel=TRUE),
      region = cog(state.region[state.abb == ifelse(st == "DC", "MD", st)]),
      division = cog(state.division[state.abb == ifelse(st == "DC", "MD", st)]),
      medianSlope = cog(median(x$slope, na.rm=TRUE), desc = "median list price slope"),
      slopeMin = cog(min(x$slope, na.rm=TRUE)),
      slopeMax = cog(max(x$slope, na.rm=TRUE)),
      latMin = cog(min(x$lat, na.rm=TRUE)),
      latMax = cog(max(x$lat, na.rm=TRUE)),
      lonMin = cog(min(x$lon, na.rm=TRUE)),
      lonMax = cog(max(x$lon, na.rm=TRUE))
   )   
}

\# Make the new display
makeDisplay(slopesByState,
   name = "county_price_changes_for_each_state",
   desc = "County level trends in prices for each state",
   panelFn = stateMapPanelFn, 
   cogFn = mapCog,
   width = 400, height = 400)

\# Open trelliscope
view(port=8100)

\##NOTE: look at the second display county_price_changes_for_each_state and verify it works

\###############################################################################
\###############################################################################
\###############################################################################
\###############################################################################

\### now remove all objects and try loading vdb
\### look at the second display county_price_changes_for_each_state 
\### map does not load and you will see this message on the console:
\### errorError in fn(kvPair[[2]]) : 
\###  could not find function "matchMapRegionToCounty"

rm(list = ls())
ls()

vdbConn("vdb_housing", autoYes = TRUE)
view(port = 8100)

**Comment by amwhite** [comment]
A little more info on testing this. I tested the Feb 2 commit and it worked fine, but the Feb 3 commit does not. You can see that by doing this:
```
# Install Feb 2 version:
install_github("tesseradata/trelliscope@d372c33549eae4ba0597c78e60d898fbdf2e7dcb")
# Run the test script above and it should work fine.

# install Feb3 version:
install_github("tesseradata/trelliscope@f999cf475ce676f2ce9f4b7d8844f0a848c6a7fb")
# Re-run test script above and get the error at the end.
```

**Comment by hafen** [comment]
Yes I just noticed this as well.  I know what the problem is and will get on it.

**Comment by amwhite** [comment]
I think this bug is not fully fixed, I'm experiencing this problem again. I've installed the latest versions of trelliscope and datadr as of 2015-04-10. Here's how to recreate it:

```
## This generates the vdb and launches it. Trelliscope works fine here.
source("regenerate_netflow_vdb.R")

## Clear environment and reconnect to vdb created in above script:
rm(list=ls())
vdbConn("vdb_netflow")
view(port=56745)
```
Then I get the following error in the console:
```
attempting to launch shiny vdb viewer...
press Ctrl+C or Esc to stop viewer

Listening on http://127.0.0.1:56745
Loading required package: htmlwidgets
Error in plot.igraph(pairsGraph, layout = layout, vertex.label = "", vertex.size = 6,  : 
  object 'pairsGraph' not found
```
'pairsGraph' is the name of a data object used to create the trelliscope display.  @hafen I'll send you the full code and data needed to recreate this.

**Comment by hafen** [comment]
I ran through the code and I'm not sure why the variables are not picked up, but it has to do with the `findGlobals()` function in the codetools package.  If that function can not find a global, then trelliscope can't do it either.  It's always been pretty good at finding things.  But in cases like these, this is why the `params` argument exists in `makeDisplay()`, where you can specify your globals explicitly.  For example, add the following line to your call to `makeDisplay()`:

```
params = list(pairsGraph = pairsGraph, ipPairs = ipPairs)
```

I had to make a tweak to the code and I don't have time to test it at the moment, but you can try it out with `install_github("hafen/trelliscope")`.

**Comment by hafen** [comment]
I've made updates to datadr and trelliscope that will allow `params=list(...)` to work correctly.
