### ISSUE TITLE
ghost boxes 

### ISSUE THREAD

**Issue by mrswaterworth** [tesseradata/trelliscope#88]
In Trelliscope, I go into the Related Displays for and select a graph to display, which pops up two blue boxes representing the two graphs.

1. If I click out of the form without selecting Cancel or Apply, the blue boxes remain superimposed over the graph once the form closes.

![example1](https://cloud.githubusercontent.com/assets/10344211/6193102/f50d7a0e-b36c-11e4-887b-289ad00955d9.png)

2.  I interpret the two blue boxes to be how I will display the two graphs for comparison.  However, I can only slide the boxes on top of each other rather than switching the positions of the graphs.  When I slide the boxes on top of each other and select Apply, I only see the graph on top.

![example2](https://cloud.githubusercontent.com/assets/10344211/6193138/2deaa194-b36d-11e4-8601-66894f7bfa19.png)

**Comment by hafen** [comment]
Can you provide details of your environment (browser, browser version, etc.)?  I cannot replicate on Safari/Chrome/Firefox on mac.

**Comment by mrswaterworth** [comment]
Google Chrome on Windows 7

**Comment by hafen** [comment]
Interesting.  I don't have Windows so it will be difficult to test, but I'll see what I can do.  Thanks for reporting.

**Comment by hafen** [comment]
This should be fixed in an update that will be pushed out soon.  If you want to test, try

```
devtools::install_github("hafen/trelliscope")
```
